//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18046
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EdgeEnergy.CutterDashboard.Assets.LocalizedResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EdgeEnergy.CutterDashboard.Assets.LocalizedResources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 MONTH.
        /// </summary>
        public static string _1_MONTH {
            get {
                return ResourceManager.GetString("_1_MONTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 YEAR.
        /// </summary>
        public static string _1_YEAR {
            get {
                return ResourceManager.GetString("_1_YEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10 YEARS.
        /// </summary>
        public static string _10_YEARS {
            get {
                return ResourceManager.GetString("_10_YEARS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 MONTHS.
        /// </summary>
        public static string _3_MONTHS {
            get {
                return ResourceManager.GetString("_3_MONTHS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 YEARS.
        /// </summary>
        public static string _5_YEARS {
            get {
                return ResourceManager.GetString("_5_YEARS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 52 Weeks.
        /// </summary>
        public static string _52_Weeks {
            get {
                return ResourceManager.GetString("_52_Weeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6 MONTHS.
        /// </summary>
        public static string _6_MONTHS {
            get {
                return ResourceManager.GetString("_6_MONTHS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to www,OneSrc.co.uk.
        /// </summary>
        public static string AboutSite {
            get {
                return ResourceManager.GetString("AboutSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designed by One Source for Edge Energy.
        /// </summary>
        public static string AboutText {
            get {
                return ResourceManager.GetString("AboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version 2.0.
        /// </summary>
        public static string AboutVersion {
            get {
                return ResourceManager.GetString("AboutVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD.
        /// </summary>
        public static string ADD {
            get {
                return ResourceManager.GetString("ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask.
        /// </summary>
        public static string Ask {
            get {
                return ResourceManager.GetString("Ask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bid.
        /// </summary>
        public static string Bid {
            get {
                return ResourceManager.GetString("Bid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change %.
        /// </summary>
        public static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area Chart.
        /// </summary>
        public static string Chart_Area {
            get {
                return ResourceManager.GetString("Chart_Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare stock performance against a baseline (e.g., Dow average)..
        /// </summary>
        public static string Chart_Area_Desc {
            get {
                return ResourceManager.GetString("Chart_Area_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Candle Stick Chart.
        /// </summary>
        public static string Chart_CandleStick {
            get {
                return ResourceManager.GetString("Chart_CandleStick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See how stock performs each day along with its volume of trading..
        /// </summary>
        public static string Chart_CandleStick_Desc {
            get {
                return ResourceManager.GetString("Chart_CandleStick_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Chart.
        /// </summary>
        public static string Chart_Line {
            get {
                return ResourceManager.GetString("Chart_Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track simple price changes over time..
        /// </summary>
        public static string Chart_Line_Desc {
            get {
                return ResourceManager.GetString("Chart_Line_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O-H-L-C.
        /// </summary>
        public static string Chart_OHLC {
            get {
                return ResourceManager.GetString("Chart_OHLC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See how the stock performs opening and closing each day..
        /// </summary>
        public static string Chart_OHLC_Desc {
            get {
                return ResourceManager.GetString("Chart_OHLC_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Chart Type:.
        /// </summary>
        public static string Choose_Chart_Type {
            get {
                return ResourceManager.GetString("Choose_Chart_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on an Industry node to view it&apos;s child companies.
        /// </summary>
        public static string Company_Summary_Info {
            get {
                return ResourceManager.GetString("Company_Summary_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily High.
        /// </summary>
        public static string Daily_High {
            get {
                return ResourceManager.GetString("Daily_High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily Low.
        /// </summary>
        public static string Daily_Low {
            get {
                return ResourceManager.GetString("Daily_Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Div. Yield %.
        /// </summary>
        public static string Div_Yield {
            get {
                return ResourceManager.GetString("Div_Yield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EBITA.
        /// </summary>
        public static string EBITA {
            get {
                return ResourceManager.GetString("EBITA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EPS.
        /// </summary>
        public static string EPS {
            get {
                return ResourceManager.GetString("EPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FTP.
        /// </summary>
        public static string FileFtp {
            get {
                return ResourceManager.GetString("FileFtp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        public static string FileOpen {
            get {
                return ResourceManager.GetString("FileOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string FileSave {
            get {
                return ResourceManager.GetString("FileSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Realtime.
        /// </summary>
        public static string FileTcp {
            get {
                return ResourceManager.GetString("FileTcp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File + RT.
        /// </summary>
        public static string FileTcpFile {
            get {
                return ResourceManager.GetString("FileTcpFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net Profit
        ///Margin.
        /// </summary>
        public static string Grid_Net_Profit_Margin {
            get {
                return ResourceManager.GetString("Grid_Net_Profit_Margin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price to Book
        ///Value (mrq).
        /// </summary>
        public static string Grid_Price_to_Book {
            get {
                return ResourceManager.GetString("Grid_Price_to_Book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price to Free
        ///Cash Flow (mrq).
        /// </summary>
        public static string Grid_Price_to_Free_Cash_Flow {
            get {
                return ResourceManager.GetString("Grid_Price_to_Free_Cash_Flow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heat Map.
        /// </summary>
        public static string Heat_Map {
            get {
                return ResourceManager.GetString("Heat_Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left-click on a black Sector node to drill down and right-click to go back..
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        public static string LOAD {
            get {
                return ResourceManager.GetString("LOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market Cap.
        /// </summary>
        public static string Market_Cap {
            get {
                return ResourceManager.GetString("Market_Cap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Market.
        /// </summary>
        public static string Market_Description {
            get {
                return ResourceManager.GetString("Market_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAX.
        /// </summary>
        public static string MAX {
            get {
                return ResourceManager.GetString("MAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mkt Cap.
        /// </summary>
        public static string Mkt_Cap {
            get {
                return ResourceManager.GetString("Mkt_Cap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net Profit Margin.
        /// </summary>
        public static string Net_Profit_Margin {
            get {
                return ResourceManager.GetString("Net_Profit_Margin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P/E.
        /// </summary>
        public static string P_E {
            get {
                return ResourceManager.GetString("P_E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P/E.
        /// </summary>
        public static string PE {
            get {
                return ResourceManager.GetString("PE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait....
        /// </summary>
        public static string Please_Wait {
            get {
                return ResourceManager.GetString("Please_Wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Price_Over_Time {
            get {
                return ResourceManager.GetString("Price_Over_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price to Book Value (mrq).
        /// </summary>
        public static string Price_to_Book {
            get {
                return ResourceManager.GetString("Price_to_Book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price to Free Cash Flow (mrq).
        /// </summary>
        public static string Price_to_Free_Cash_Flow {
            get {
                return ResourceManager.GetString("Price_to_Free_Cash_Flow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range.
        /// </summary>
        public static string Range {
            get {
                return ResourceManager.GetString("Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ROE %.
        /// </summary>
        public static string ROE {
            get {
                return ResourceManager.GetString("ROE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Sales_Volume {
            get {
                return ResourceManager.GetString("Sales_Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Stock_Price {
            get {
                return ResourceManager.GetString("Stock_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to load.
        /// </summary>
        public static string Stocks_Chart {
            get {
                return ResourceManager.GetString("Stocks_Chart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type field here.
        /// </summary>
        public static string Type_Ticker_Here {
            get {
                return ResourceManager.GetString("Type_Ticker_Here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vol.
        /// </summary>
        public static string Vol {
            get {
                return ResourceManager.GetString("Vol", resourceCulture);
            }
        }
    }
}
